### ISSUE TITLE
Cannot create thumbnails

### ISSUE THREAD

**Issue by lekhnath** [aguidrevitch/jquery-file-upload-middleware#34]
This middle ware is working fine but when trying to upload image files the thumbnails are not created and the server is halted. When ever I try to upload image files I get the below message logged in my terminal :

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)
10 Nov 12:30:41 - [nodemon] app crashed - waiting for file changes before starting...

I have installed 'swig' and 'imagemagick' dependencies also.

**Comment by johnny12150** [comment]
Still a super useful info.
