### ISSUE TITLE
not maintained anymore?

### ISSUE THREAD

**Issue by Jeff2Ma** [aguidrevitch/jquery-file-upload-middleware#74]
Hi, sir. while using this middleware in my project. A console log show as list:

> express deprecated res.json(status, obj): Use res.status(status).json(obj) instead node_modules/jquery-file-upload-middleware/lib/filehandler.js:19:21

 it seems like the code is too old, is this project not maintained anymore? sorry for my poor english :)

**Comment by mberlanda** [comment]
+1

**Comment by aguidrevitch** [comment]
fixed in 0.1.8
